### PR TITLE
Update test.tf

### PR DESCRIPTION
**Pull request by acidflash**
Gör ny resource "null_resource" "example3" {}

### CODE REVIEW

**Comment by ss-atlantis** [comment]
Ran Plan for project: `ss-test` dir: `ss-test` workspace: `default`

<details><summary>Show Output</summary>

```diff
preint


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example will be created
+ resource "null_resource" "example" {
      + id = (known after apply)
    }

  # null_resource.example1 will be created
+ resource "null_resource" "example1" {
      + id = (known after apply)
    }

  # null_resource.example3 will be created
+ resource "null_resource" "example3" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p ss-test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis:4141/lock?id=Sentor-OPS-Team%252FAWS%252Fss-test%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p ss-test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by acidflash** [comment]
atlantis apply

**Comment by ss-atlantis** [comment]
Ran Apply for project: `ss-test` dir: `ss-test` workspace: `default`

<details><summary>Show Output</summary>

```diff
applying

null_resource.example1: Creating...
null_resource.example3: Creating...
null_resource.example: Creating...
null_resource.example1: Creation complete after 0s [id=4066315204836685678]
null_resource.example: Creation complete after 0s [id=710117970143945028]
null_resource.example3: Creation complete after 0s [id=1833937809270255613]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by ss-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `ss-test` workspace: `default`

**Pull request merged**
